import type { GlobalConfig } from "payload";

export const BlogTimingSettings: GlobalConfig = {
  slug: "blog-timing-settings",
  label: "Blog Timing Settings",
  admin: {
    group: "Blog",
  },
  fields: [
    {
      name: "recommendedSlot",
      type: "select",
      defaultValue: "none",
      options: [
        { label: "None (not yet optimized)", value: "none" },
        { label: "9:00 AM", value: "9am" },
        { label: "2:00 PM", value: "2pm" },
        { label: "7:00 PM", value: "7pm" },
      ],
      admin: {
        description: "Recommended publish time slot based on A/B testing analysis.",
      },
    },
    {
      name: "recommendationReason",
      type: "textarea",
      admin: {
        description: "Why this slot was recommended. Generated by Claude.",
      },
    },
    {
      name: "lastAnalyzedAt",
      type: "date",
      admin: {
        description: "When the optimization was last run.",
      },
    },
    {
      name: "publishedBlogCount",
      type: "number",
      defaultValue: 0,
      admin: {
        description: "Total blogs published (used to know when enough data for analysis).",
      },
    },
    {
      name: "slotStats",
      type: "array",
      fields: [
        {
          name: "slot",
          type: "text",
          required: true,
        },
        {
          name: "avgViews",
          type: "number",
        },
        {
          name: "avgScrollDepth",
          type: "number",
          admin: {
            description: "Average scroll depth percentage (0-100).",
          },
        },
        {
          name: "avgTimeOnPage",
          type: "number",
          admin: {
            description: "Average time on page in seconds.",
          },
        },
        {
          name: "blogCount",
          type: "number",
          admin: {
            description: "How many blogs tested with this slot.",
          },
        },
      ],
      admin: {
        description: "Performance metrics per A/B test slot.",
      },
    },
  ],
};
