/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    'sub-categories': SubCategory;
    shapes: Shape;
    occasions: Occasion;
    products: Product;
    'diamond-categories': DiamondCategory;
    'color-stones': ColorStone;
    'rate-gold': RateGold;
    'rate-diamond': RateDiamond;
    'making-rules': MakingRule;
    'fx-rates': FxRate;
    reviews: Review;
    faqs: Faq;
    'trust-badges': TrustBadge;
    customers: Customer;
    'try-at-home-leads': TryAtHomeLead;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'sub-categories': SubCategoriesSelect<false> | SubCategoriesSelect<true>;
    shapes: ShapesSelect<false> | ShapesSelect<true>;
    occasions: OccasionsSelect<false> | OccasionsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'diamond-categories': DiamondCategoriesSelect<false> | DiamondCategoriesSelect<true>;
    'color-stones': ColorStonesSelect<false> | ColorStonesSelect<true>;
    'rate-gold': RateGoldSelect<false> | RateGoldSelect<true>;
    'rate-diamond': RateDiamondSelect<false> | RateDiamondSelect<true>;
    'making-rules': MakingRulesSelect<false> | MakingRulesSelect<true>;
    'fx-rates': FxRatesSelect<false> | FxRatesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'trust-badges': TrustBadgesSelect<false> | TrustBadgesSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    'try-at-home-leads': TryAtHomeLeadsSelect<false> | TryAtHomeLeadsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'feature-flags': FeatureFlag;
    'try-at-home-settings': TryAtHomeSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'feature-flags': FeatureFlagsSelect<false> | FeatureFlagsSelect<true>;
    'try-at-home-settings': TryAtHomeSettingsSelect<false> | TryAtHomeSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Customer;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    zoom?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * URL-safe identifier, e.g. 'rings', 'earrings'.
   */
  slug: string;
  sortOrder?: number | null;
  heroImage?: (number | null) | Media;
  shortDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sub-categories".
 */
export interface SubCategory {
  id: number;
  name: string;
  /**
   * URL-safe identifier, e.g. 'halo', 'trilogy'.
   */
  slug: string;
  category: number | Category;
  sortOrder?: number | null;
  heroImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shapes".
 */
export interface Shape {
  id: number;
  name: string;
  slug: string;
  sortOrder?: number | null;
  /**
   * Small SVG icon shown in 'Shop by Shape'.
   */
  icon?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "occasions".
 */
export interface Occasion {
  id: number;
  name: string;
  slug: string;
  sortOrder?: number | null;
  heroImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Style code, e.g. 'ER-001'. Natural key for imports + image folder lookup.
   */
  code: string;
  status?: ('draft' | 'active' | 'archived') | null;
  /**
   * Auto-derived from code if blank.
   */
  slug?: string | null;
  /**
   * Customer-facing title. e.g. 'Cushion Cut Halo Engagement Ring'.
   */
  displayName: string;
  description?: string | null;
  category: number | Category;
  subCategory?: (number | null) | SubCategory;
  primaryShape?: (number | null) | Shape;
  /**
   * If true, customer can pick 1ct / 2ct / 3ct diamond size variants.
   */
  isSolitaire?: boolean | null;
  /**
   * If true, customer picks ring size (US 4–13). Auto-set on save if category=Rings.
   */
  isRing?: boolean | null;
  fulfillmentType: 'made_to_order' | 'ready_stock';
  /**
   * Units available. Only used for Ready Stock.
   */
  stockQuantity?: number | null;
  heroImage?: (number | null) | Media;
  /**
   * Which gold color variant to show by default on the storefront. Gold → Yellow, Silver/Platinum → White. Override per-product if needed.
   */
  defaultGoldColor?: ('yellow' | 'white' | 'rose') | null;
  /**
   * All product images. Tag each with its gold color so the storefront gallery switches images when the customer picks Yellow / White / Rose Gold. Leave color as 'Any' for lifestyle/model shots that look good in all variants.
   */
  gallery?:
    | {
        image: number | Media;
        /**
         * Which gold color variant this image represents.
         */
        goldColor?: ('' | 'yellow' | 'white' | 'rose') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Cheapest variant (9K + Lab Standard), incl. GST. Auto-computed by `pnpm refresh:prices`. Drives collection filtering + sorting.
   */
  fromPriceInr?: number | null;
  metals?:
    | {
        purity: '9K' | '14K' | '18K' | '22K' | 'Silver925' | 'Platinum';
        /**
         * Grams of metal at this purity.
         */
        weightG: number;
        id?: string | null;
      }[]
    | null;
  diamonds?:
    | {
        role: 'small' | 'solitaire';
        shape?: (number | null) | Shape;
        /**
         * Stone dimensions, e.g. '1.85*1.85' or '6.00*4.00'.
         */
        sizeMm?: string | null;
        /**
         * Total carat weight (sum of all stones in this row).
         */
        weightCt: number;
        count: number;
        cut?: string | null;
        color?: string | null;
        clarity?: string | null;
        id?: string | null;
      }[]
    | null;
  colorStones?:
    | {
        stone: number | ColorStone;
        weightCt: number;
        count: number;
        id?: string | null;
      }[]
    | null;
  designerNotes?: string | null;
  remarks?: string | null;
  complementaryProducts?: (number | Product)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "color-stones".
 */
export interface ColorStone {
  id: number;
  name: string;
  /**
   * URL-safe: 'ruby', 'emerald', 'blue-sapphire'.
   */
  slug: string;
  grade?: ('Premium' | 'Standard') | null;
  /**
   * INR per carat. Editable anytime.
   */
  ratePerCt: number;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "diamond-categories".
 */
export interface DiamondCategory {
  id: number;
  name: string;
  /**
   * URL-safe identifier: 'natural', 'lab-premium', 'lab-standard'.
   */
  slug: string;
  description?: string | null;
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Per-gram INR rate per purity. Pricing engine uses the most recent row for each purity.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rate-gold".
 */
export interface RateGold {
  id: number;
  purity: '9K' | '14K' | '18K' | '22K' | 'Silver925' | 'Platinum';
  /**
   * INR per gram.
   */
  ratePerG: number;
  source?: ('manual' | 'ibja' | 'imported') | null;
  effectiveAt: string;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Per-carat INR rate by diamond category × carat band. Add 4Cs-specific rows for finer pricing later.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rate-diamond".
 */
export interface RateDiamond {
  id: number;
  diamondCategory: number | DiamondCategory;
  /**
   * Inclusive lower bound, e.g. 0.00
   */
  ctBandMin: number;
  /**
   * Exclusive upper bound, e.g. 1.00
   */
  ctBandMax: number;
  /**
   * INR per carat. Whole stone is multiplied by this rate.
   */
  ratePerCt: number;
  /**
   * Optional, e.g. 'Excellent'. Leave blank for any.
   */
  cut?: string | null;
  /**
   * Optional, e.g. 'G'. Leave blank for any.
   */
  color?: string | null;
  /**
   * Optional, e.g. 'SI'. Leave blank for any.
   */
  clarity?: string | null;
  effectiveAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Making charges per metal type. Edit anytime — affects every product using that metal immediately.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "making-rules".
 */
export interface MakingRule {
  id: number;
  metalType: 'gold' | 'silver' | 'platinum';
  type: 'wastage_plus_making' | 'flat';
  /**
   * Wastage % (only for Wastage+Making mode)
   */
  wastagePct?: number | null;
  /**
   * INR per gram of metal
   */
  makingPerG: number;
  /**
   * Minimum making charge (floor)
   */
  minMaking?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * How many INR for 1 unit of each foreign currency. Edit anytime.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fx-rates".
 */
export interface FxRate {
  id: number;
  currency: 'USD' | 'AED' | 'GBP' | 'EUR' | 'SGD';
  /**
   * ₹ per 1 unit of this currency, e.g. 85 for USD
   */
  inrPerUnit: number;
  source?: ('manual' | 'api') | null;
  effectiveAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  product: number | Product;
  /**
   * 1–5 stars
   */
  rating: number;
  title: string;
  body: string;
  authorName: string;
  /**
   * Date shown on storefront. Defaults to creation date.
   */
  reviewDate?: string | null;
  /**
   * Verified purchase
   */
  verified?: boolean | null;
  /**
   * Show publicly
   */
  approved?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * FAQ accordion shown on all product pages. Drag rows or set 'order' to control sequence.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  category?: ('general' | 'diamonds' | 'pricing' | 'returns' | 'shipping') | null;
  /**
   * Lower = appears first
   */
  order?: number | null;
  /**
   * Uncheck to hide on site
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Configurable trust badges shown on the product page below the Buy button.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trust-badges".
 */
export interface TrustBadge {
  id: number;
  /**
   * Emoji or symbol (e.g. ✦ ✓ 🔄 🚚)
   */
  icon: string;
  label: string;
  /**
   * Shown on hover — keep under 120 characters.
   */
  tooltip?: string | null;
  /**
   * Lower = appears first
   */
  order?: number | null;
  /**
   * Visible on site
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  fullName?: string | null;
  /**
   * WhatsApp number is the universal customer key. Include country code.
   */
  phone?: string | null;
  waOptIn?: boolean | null;
  segments?: ('new' | 'engaged' | 'high_value' | 'vip' | 'dormant')[] | null;
  /**
   * Where this customer entered: 'web', 'wa', 'referral', etc.
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * Home-trial leads from the 'Try at Home' card on product pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "try-at-home-leads".
 */
export interface TryAtHomeLead {
  id: number;
  customerName: string;
  phone: string;
  email?: string | null;
  address: string;
  city?: string | null;
  state?: string | null;
  pincode?: string | null;
  /**
   * e.g. RR-052
   */
  productCode?: string | null;
  productName?: string | null;
  status?: ('new' | 'contacted' | 'scheduled' | 'converted' | 'rejected') | null;
  /**
   * Internal notes — not visible to the customer
   */
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'sub-categories';
        value: number | SubCategory;
      } | null)
    | ({
        relationTo: 'shapes';
        value: number | Shape;
      } | null)
    | ({
        relationTo: 'occasions';
        value: number | Occasion;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'diamond-categories';
        value: number | DiamondCategory;
      } | null)
    | ({
        relationTo: 'color-stones';
        value: number | ColorStone;
      } | null)
    | ({
        relationTo: 'rate-gold';
        value: number | RateGold;
      } | null)
    | ({
        relationTo: 'rate-diamond';
        value: number | RateDiamond;
      } | null)
    | ({
        relationTo: 'making-rules';
        value: number | MakingRule;
      } | null)
    | ({
        relationTo: 'fx-rates';
        value: number | FxRate;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'trust-badges';
        value: number | TrustBadge;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'try-at-home-leads';
        value: number | TryAtHomeLead;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        zoom?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  sortOrder?: T;
  heroImage?: T;
  shortDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sub-categories_select".
 */
export interface SubCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  sortOrder?: T;
  heroImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shapes_select".
 */
export interface ShapesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  sortOrder?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "occasions_select".
 */
export interface OccasionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  sortOrder?: T;
  heroImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  code?: T;
  status?: T;
  slug?: T;
  displayName?: T;
  description?: T;
  category?: T;
  subCategory?: T;
  primaryShape?: T;
  isSolitaire?: T;
  isRing?: T;
  fulfillmentType?: T;
  stockQuantity?: T;
  heroImage?: T;
  defaultGoldColor?: T;
  gallery?:
    | T
    | {
        image?: T;
        goldColor?: T;
        id?: T;
      };
  fromPriceInr?: T;
  metals?:
    | T
    | {
        purity?: T;
        weightG?: T;
        id?: T;
      };
  diamonds?:
    | T
    | {
        role?: T;
        shape?: T;
        sizeMm?: T;
        weightCt?: T;
        count?: T;
        cut?: T;
        color?: T;
        clarity?: T;
        id?: T;
      };
  colorStones?:
    | T
    | {
        stone?: T;
        weightCt?: T;
        count?: T;
        id?: T;
      };
  designerNotes?: T;
  remarks?: T;
  complementaryProducts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "diamond-categories_select".
 */
export interface DiamondCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "color-stones_select".
 */
export interface ColorStonesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  grade?: T;
  ratePerCt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rate-gold_select".
 */
export interface RateGoldSelect<T extends boolean = true> {
  purity?: T;
  ratePerG?: T;
  source?: T;
  effectiveAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rate-diamond_select".
 */
export interface RateDiamondSelect<T extends boolean = true> {
  diamondCategory?: T;
  ctBandMin?: T;
  ctBandMax?: T;
  ratePerCt?: T;
  cut?: T;
  color?: T;
  clarity?: T;
  effectiveAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "making-rules_select".
 */
export interface MakingRulesSelect<T extends boolean = true> {
  metalType?: T;
  type?: T;
  wastagePct?: T;
  makingPerG?: T;
  minMaking?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fx-rates_select".
 */
export interface FxRatesSelect<T extends boolean = true> {
  currency?: T;
  inrPerUnit?: T;
  source?: T;
  effectiveAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  product?: T;
  rating?: T;
  title?: T;
  body?: T;
  authorName?: T;
  reviewDate?: T;
  verified?: T;
  approved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trust-badges_select".
 */
export interface TrustBadgesSelect<T extends boolean = true> {
  icon?: T;
  label?: T;
  tooltip?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  fullName?: T;
  phone?: T;
  waOptIn?: T;
  segments?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "try-at-home-leads_select".
 */
export interface TryAtHomeLeadsSelect<T extends boolean = true> {
  customerName?: T;
  phone?: T;
  email?: T;
  address?: T;
  city?: T;
  state?: T;
  pincode?: T;
  productCode?: T;
  productName?: T;
  status?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Site-wide configuration. Disclaimer text, badges, copy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Shown on PDP and quote PDFs for made-to-order products.
   */
  madeToOrderDisclaimer?: string | null;
  /**
   * Shown on PDP for ready-stock products.
   */
  readyStockBadgeText?: string | null;
  readyStockPriceNote?: string | null;
  /**
   * How long a generated quote stays valid before gold-rate movement requires a fresh quote.
   */
  quoteValidityDays?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Master switches for every external integration. When a switch is OFF, a safe manual fallback runs. Flip ON only after you've tested the integration.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feature-flags".
 */
export interface FeatureFlag {
  id: number;
  wa_business_api?: boolean | null;
  wa_shared_inbox?: boolean | null;
  wa_login?: boolean | null;
  ai_draft_replies?: boolean | null;
  ai_web_chatbot?: boolean | null;
  ai_voice_agent?: boolean | null;
  ai_reference_image_search?: boolean | null;
  gold_rate_live_ibja?: boolean | null;
  gold_rate_auto_recompute?: boolean | null;
  fx_live?: boolean | null;
  checkout_cashfree?: boolean | null;
  checkout_gst_invoice_pdf?: boolean | null;
  shipping_serviceability?: boolean | null;
  meta_capi_server_side?: boolean | null;
  email_transactional?: boolean | null;
  email_campaigns?: boolean | null;
  campaigns_scheduled_sends?: boolean | null;
  search_semantic_pgvector?: boolean | null;
  similar_products_vector?: boolean | null;
  scraper_competitor_designs?: boolean | null;
  wallet_cashback_engine?: boolean | null;
  wallet_loyalty_points?: boolean | null;
  i18n_hindi?: boolean | null;
  i18n_other_languages?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Controls the 'Try at Home' lead-generation card shown on product pages. Leads are saved under CRM → Try at Home Leads.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "try-at-home-settings".
 */
export interface TryAtHomeSetting {
  id: number;
  enabled?: boolean | null;
  /**
   * Heading shown on the card
   */
  title?: string | null;
  /**
   * Body text shown below the heading
   */
  description?: string | null;
  /**
   * CTA button label
   */
  buttonText?: string | null;
  /**
   * Optional lifestyle image shown on the left of the card (landscape works best)
   */
  image?: (number | null) | Media;
  /**
   * Optional small-print shown below the form (e.g. 'Available in Jaipur & Delhi only')
   */
  disclaimer?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  madeToOrderDisclaimer?: T;
  readyStockBadgeText?: T;
  readyStockPriceNote?: T;
  quoteValidityDays?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feature-flags_select".
 */
export interface FeatureFlagsSelect<T extends boolean = true> {
  wa_business_api?: T;
  wa_shared_inbox?: T;
  wa_login?: T;
  ai_draft_replies?: T;
  ai_web_chatbot?: T;
  ai_voice_agent?: T;
  ai_reference_image_search?: T;
  gold_rate_live_ibja?: T;
  gold_rate_auto_recompute?: T;
  fx_live?: T;
  checkout_cashfree?: T;
  checkout_gst_invoice_pdf?: T;
  shipping_serviceability?: T;
  meta_capi_server_side?: T;
  email_transactional?: T;
  email_campaigns?: T;
  campaigns_scheduled_sends?: T;
  search_semantic_pgvector?: T;
  similar_products_vector?: T;
  scraper_competitor_designs?: T;
  wallet_cashback_engine?: T;
  wallet_loyalty_points?: T;
  i18n_hindi?: T;
  i18n_other_languages?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "try-at-home-settings_select".
 */
export interface TryAtHomeSettingsSelect<T extends boolean = true> {
  enabled?: T;
  title?: T;
  description?: T;
  buttonText?: T;
  image?: T;
  disclaimer?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}