/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    'sub-categories': SubCategory;
    shapes: Shape;
    occasions: Occasion;
    products: Product;
    'diamond-categories': DiamondCategory;
    'color-stones': ColorStone;
    'rate-gold': RateGold;
    'rate-diamond': RateDiamond;
    'making-rules': MakingRule;
    'fx-rates': FxRate;
    reviews: Review;
    'collection-banners': CollectionBanner;
    'collection-marketing-tiles': CollectionMarketingTile;
    faqs: Faq;
    'trust-badges': TrustBadge;
    customers: Customer;
    'try-at-home-leads': TryAtHomeLead;
    orders: Order;
    events: Event;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'sub-categories': SubCategoriesSelect<false> | SubCategoriesSelect<true>;
    shapes: ShapesSelect<false> | ShapesSelect<true>;
    occasions: OccasionsSelect<false> | OccasionsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'diamond-categories': DiamondCategoriesSelect<false> | DiamondCategoriesSelect<true>;
    'color-stones': ColorStonesSelect<false> | ColorStonesSelect<true>;
    'rate-gold': RateGoldSelect<false> | RateGoldSelect<true>;
    'rate-diamond': RateDiamondSelect<false> | RateDiamondSelect<true>;
    'making-rules': MakingRulesSelect<false> | MakingRulesSelect<true>;
    'fx-rates': FxRatesSelect<false> | FxRatesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'collection-banners': CollectionBannersSelect<false> | CollectionBannersSelect<true>;
    'collection-marketing-tiles': CollectionMarketingTilesSelect<false> | CollectionMarketingTilesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'trust-badges': TrustBadgesSelect<false> | TrustBadgesSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    'try-at-home-leads': TryAtHomeLeadsSelect<false> | TryAtHomeLeadsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'feature-flags': FeatureFlag;
    'try-at-home-settings': TryAtHomeSetting;
    'home-page': HomePage;
    'chatbot-config': ChatbotConfig;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'feature-flags': FeatureFlagsSelect<false> | FeatureFlagsSelect<true>;
    'try-at-home-settings': TryAtHomeSettingsSelect<false> | TryAtHomeSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'chatbot-config': ChatbotConfigSelect<false> | ChatbotConfigSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Customer;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    zoom?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * URL-safe identifier, e.g. 'rings', 'earrings'.
   */
  slug: string;
  sortOrder?: number | null;
  heroImage?: (number | null) | Media;
  shortDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sub-categories".
 */
export interface SubCategory {
  id: number;
  name: string;
  /**
   * URL-safe identifier, e.g. 'halo', 'trilogy'.
   */
  slug: string;
  category: number | Category;
  sortOrder?: number | null;
  heroImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shapes".
 */
export interface Shape {
  id: number;
  name: string;
  slug: string;
  sortOrder?: number | null;
  /**
   * Small SVG icon shown in 'Shop by Shape'.
   */
  icon?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "occasions".
 */
export interface Occasion {
  id: number;
  name: string;
  slug: string;
  sortOrder?: number | null;
  heroImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Style code, e.g. 'ER-001'. Natural key for imports + image folder lookup.
   */
  code: string;
  status?: ('draft' | 'active' | 'archived') | null;
  /**
   * Auto-derived from code if blank.
   */
  slug?: string | null;
  /**
   * Customer-facing title. e.g. 'Cushion Cut Halo Engagement Ring'.
   */
  displayName: string;
  description?: string | null;
  category: number | Category;
  subCategory?: (number | null) | SubCategory;
  primaryShape?: (number | null) | Shape;
  /**
   * If true, customer can pick 1ct / 2ct / 3ct diamond size variants.
   */
  isSolitaire?: boolean | null;
  /**
   * If true, customer picks ring size (US 4–13). Auto-set on save if category=Rings.
   */
  isRing?: boolean | null;
  fulfillmentType: 'made_to_order' | 'ready_stock';
  /**
   * Units available. Only used for Ready Stock.
   */
  stockQuantity?: number | null;
  heroImage?: (number | null) | Media;
  /**
   * Which gold color variant to show by default on the storefront. Gold → Yellow, Silver/Platinum → White. Override per-product if needed.
   */
  defaultGoldColor?: ('yellow' | 'white' | 'rose') | null;
  /**
   * Hero image for Yellow Gold variant.
   */
  heroImageYellow?: (number | null) | Media;
  /**
   * Hero image for White Gold / Silver / Platinum variant.
   */
  heroImageWhite?: (number | null) | Media;
  /**
   * Hero image for Rose Gold variant.
   */
  heroImageRose?: (number | null) | Media;
  /**
   * All product images. Tag each with its gold color so the storefront gallery switches images when the customer picks Yellow / White / Rose Gold. Leave color as 'Any' for lifestyle/model shots that look good in all variants.
   */
  gallery?:
    | {
        image: number | Media;
        /**
         * Which gold color variant this image represents.
         */
        goldColor?: ('' | 'yellow' | 'white' | 'rose') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Cheapest variant (9K + Lab Standard), incl. GST. Auto-computed by `pnpm refresh:prices`. Drives collection filtering + sorting.
   */
  fromPriceInr?: number | null;
  metals?:
    | {
        purity: '9K' | '14K' | '18K' | '22K' | 'Silver925' | 'Platinum';
        /**
         * Grams of metal at this purity.
         */
        weightG: number;
        id?: string | null;
      }[]
    | null;
  diamonds?:
    | {
        role: 'small' | 'solitaire';
        shape?: (number | null) | Shape;
        /**
         * Stone dimensions, e.g. '1.85*1.85' or '6.00*4.00'.
         */
        sizeMm?: string | null;
        /**
         * Total carat weight (sum of all stones in this row).
         */
        weightCt: number;
        count: number;
        cut?: string | null;
        color?: string | null;
        clarity?: string | null;
        id?: string | null;
      }[]
    | null;
  colorStones?:
    | {
        stone: number | ColorStone;
        weightCt: number;
        count: number;
        id?: string | null;
      }[]
    | null;
  designerNotes?: string | null;
  remarks?: string | null;
  complementaryProducts?: (number | Product)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "color-stones".
 */
export interface ColorStone {
  id: number;
  name: string;
  /**
   * URL-safe: 'ruby', 'emerald', 'blue-sapphire'.
   */
  slug: string;
  grade?: ('Premium' | 'Standard') | null;
  /**
   * INR per carat. Editable anytime.
   */
  ratePerCt: number;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "diamond-categories".
 */
export interface DiamondCategory {
  id: number;
  name: string;
  /**
   * URL-safe identifier: 'natural', 'lab-premium', 'lab-standard'.
   */
  slug: string;
  description?: string | null;
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Per-gram INR rate per purity. Pricing engine uses the most recent row for each purity.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rate-gold".
 */
export interface RateGold {
  id: number;
  purity: '9K' | '14K' | '18K' | '22K' | 'Silver925' | 'Platinum';
  /**
   * INR per gram.
   */
  ratePerG: number;
  source?: ('manual' | 'ibja' | 'imported') | null;
  effectiveAt: string;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Per-carat INR rate by diamond category × carat band. Add 4Cs-specific rows for finer pricing later.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rate-diamond".
 */
export interface RateDiamond {
  id: number;
  diamondCategory: number | DiamondCategory;
  /**
   * Inclusive lower bound, e.g. 0.00
   */
  ctBandMin: number;
  /**
   * Exclusive upper bound, e.g. 1.00
   */
  ctBandMax: number;
  /**
   * INR per carat. Whole stone is multiplied by this rate.
   */
  ratePerCt: number;
  /**
   * Optional, e.g. 'Excellent'. Leave blank for any.
   */
  cut?: string | null;
  /**
   * Optional, e.g. 'G'. Leave blank for any.
   */
  color?: string | null;
  /**
   * Optional, e.g. 'SI'. Leave blank for any.
   */
  clarity?: string | null;
  effectiveAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Making charges per metal type. Edit anytime — affects every product using that metal immediately.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "making-rules".
 */
export interface MakingRule {
  id: number;
  metalType: 'gold' | 'silver' | 'platinum';
  type: 'wastage_plus_making' | 'flat';
  /**
   * Wastage % (only for Wastage+Making mode)
   */
  wastagePct?: number | null;
  /**
   * INR per gram of metal
   */
  makingPerG: number;
  /**
   * Minimum making charge (floor)
   */
  minMaking?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * How many INR for 1 unit of each foreign currency. Edit anytime.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fx-rates".
 */
export interface FxRate {
  id: number;
  currency: 'USD' | 'AED' | 'GBP' | 'EUR' | 'SGD';
  /**
   * ₹ per 1 unit of this currency, e.g. 85 for USD
   */
  inrPerUnit: number;
  source?: ('manual' | 'api') | null;
  effectiveAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  product: number | Product;
  /**
   * 1–5 stars
   */
  rating: number;
  title: string;
  body: string;
  authorName: string;
  /**
   * Date shown on storefront. Defaults to creation date.
   */
  reviewDate?: string | null;
  /**
   * Verified purchase
   */
  verified?: boolean | null;
  /**
   * Show publicly
   */
  approved?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Hero banner shown at the top of each collection page. Drag & drop an image (or paste a URL) directly into the Image fields below.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collection-banners".
 */
export interface CollectionBanner {
  id: number;
  /**
   * Which collection page should this banner appear on?
   */
  category: number | Category;
  /**
   * Heading shown below the banner image. Appears as the page H1.
   */
  title: string;
  /**
   * Smaller tagline shown below the title.
   */
  subtitle?: string | null;
  /**
   * Optional short paragraph below the subtitle.
   */
  description?: string | null;
  /**
   * Desktop banner (landscape). Recommended: 1400 × 500 px. Drag & drop, click to browse, or paste a URL.
   */
  imageUrl: string;
  /**
   * Optional portrait/square crop shown on screens ≤ 640 px wide. Recommended: 640 × 800 px. Falls back to the desktop image if left empty. Drag & drop, click to browse, or paste a URL.
   */
  mobileImageUrl?: string | null;
  overlayOpacity?: ('0' | '15' | '30' | '50' | '65') | null;
  /**
   * Button label — e.g. 'Shop Now'
   */
  ctaText?: string | null;
  /**
   * Button destination — e.g. '/collections/rings'
   */
  ctaLink?: string | null;
  /**
   * Uncheck to hide this banner without deleting it.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Full-width promotional tiles inserted into the product grid at configurable positions. Drag & drop an image (or paste a URL) directly into the Image field below.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collection-marketing-tiles".
 */
export interface CollectionMarketingTile {
  id: number;
  /**
   * Which collection page should this tile appear on?
   */
  category: number | Category;
  /**
   * Tile heading.
   */
  title: string;
  /**
   * Short body text — keep under 120 characters for best display.
   */
  description?: string | null;
  /**
   * Tile image. Recommended: 600 × 400 px. Drag & drop, browse, or paste a URL.
   */
  imageUrl?: string | null;
  /**
   * Button label — e.g. 'Try at Home'
   */
  ctaText?: string | null;
  /**
   * Button URL
   */
  ctaLink?: string | null;
  /**
   * Tile background colour.
   */
  backgroundColor?: ('cream' | 'white' | 'blush' | 'sage' | 'blue' | 'navy' | 'gold') | null;
  /**
   * Insert this tile after the Nth product. E.g. 6 = appears between product 6 and 7.
   */
  insertAfterNthProduct?: number | null;
  /**
   * If multiple tiles share the same position, lower number = shown first.
   */
  displayOrder?: number | null;
  /**
   * Uncheck to hide this tile without deleting it.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * FAQ accordion shown on all product pages. Drag rows or set 'order' to control sequence.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  category?: ('general' | 'diamonds' | 'pricing' | 'returns' | 'shipping') | null;
  /**
   * Lower = appears first
   */
  order?: number | null;
  /**
   * Uncheck to hide on site
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Configurable trust badges shown on the product page below the Buy button.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trust-badges".
 */
export interface TrustBadge {
  id: number;
  /**
   * Emoji or symbol (e.g. ✦ ✓ 🔄 🚚)
   */
  icon: string;
  label: string;
  /**
   * Shown on hover — keep under 120 characters.
   */
  tooltip?: string | null;
  /**
   * Lower = appears first
   */
  order?: number | null;
  /**
   * Visible on site
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  fullName?: string | null;
  /**
   * WhatsApp number is the universal customer key. Include country code.
   */
  phone?: string | null;
  waOptIn?: boolean | null;
  segments?: ('new' | 'engaged' | 'high_value' | 'vip' | 'dormant')[] | null;
  /**
   * Where this customer entered: 'web', 'wa', 'referral', etc.
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * Home-trial leads from the 'Try at Home' card on product pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "try-at-home-leads".
 */
export interface TryAtHomeLead {
  id: number;
  customerName: string;
  phone: string;
  email?: string | null;
  address: string;
  city?: string | null;
  state?: string | null;
  pincode?: string | null;
  /**
   * e.g. RR-052
   */
  productCode?: string | null;
  productName?: string | null;
  status?: ('new' | 'contacted' | 'scheduled' | 'converted' | 'rejected') | null;
  leadSource?: ('try-at-home' | 'design-advisor' | 'ai-chat' | 'other') | null;
  /**
   * Customer-uploaded reference images from the Design Advisor
   */
  referenceImages?:
    | {
        /**
         * Click to open the image in a new tab
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Internal notes — not visible to the customer
   */
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer orders placed via checkout. Update fulfillment status as items move through production and dispatch.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Auto-generated. e.g. DZ-2025-0001
   */
  orderId: string;
  /**
   * Cashfree's order reference. Use for refunds.
   */
  cashfreeOrderId?: string | null;
  cashfreePaymentId?: string | null;
  paymentStatus: 'pending' | 'captured' | 'failed' | 'refunded';
  fulfillmentStatus: 'new' | 'confirmed' | 'in_production' | 'ready' | 'dispatched' | 'delivered' | 'cancelled';
  customerName: string;
  customerPhone: string;
  customerEmail: string;
  shippingAddress: {
    line1: string;
    line2?: string | null;
    city: string;
    state: string;
    pincode: string;
  };
  /**
   * Products exactly as configured at the time of purchase.
   */
  items: {
    productCode: string;
    displayName: string;
    qty?: number | null;
    metal?: string | null;
    goldColor?: string | null;
    diamondTier?: string | null;
    ringSize?: string | null;
    caratWeight?: string | null;
    unitPriceInr?: number | null;
    engraving?: string | null;
    id?: string | null;
  }[];
  subtotalInr?: number | null;
  gstInr?: number | null;
  totalInr: number;
  orderNotes?: string | null;
  gstInvoiceRequested?: boolean | null;
  /**
   * Enter after dispatching to share with customer.
   */
  trackingInfo?: string | null;
  /**
   * Not visible to the customer.
   */
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * Anonymous visitor ID (dz_timestamp_random)
   */
  visitorId: string;
  /**
   * Session ID (persists across page reloads)
   */
  sessionId: string;
  eventName:
    | 'ViewContent'
    | 'AddToCart'
    | 'ViewCart'
    | 'InitiateCheckout'
    | 'Purchase'
    | 'BlogView'
    | 'BlogScroll'
    | 'BlogEngagement'
    | 'BlogProductClick'
    | 'Search'
    | 'SearchResultClick'
    | 'ChatbotOpened'
    | 'DesignAdvisorStart'
    | 'DesignAdvisorComplete'
    | 'Contact'
    | 'Lead';
  /**
   * Flexible event payload (product code, price, blog slug, etc.)
   */
  eventData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  pageUrl: string;
  /**
   * HTTP referrer header
   */
  referrer?: string | null;
  /**
   * Browser user agent string
   */
  userAgent?: string | null;
  /**
   * Anonymized IP (last octet redacted)
   */
  ipAddress?: string | null;
  utmSource?: string | null;
  utmMedium?: string | null;
  utmCampaign?: string | null;
  utmContent?: string | null;
  /**
   * Revenue in INR (if purchase event)
   */
  revenue?: number | null;
  currency?: string | null;
  /**
   * Order ID if this is a purchase event
   */
  orderId?: string | null;
  /**
   * Blog post slug if this is a blog event
   */
  blogSlug?: string | null;
  /**
   * Scroll depth 0-100% (blog events)
   */
  scrollDepth?: number | null;
  /**
   * Time on page in seconds
   */
  timeOnPage?: number | null;
  /**
   * Event timestamp (ISO 8601)
   */
  timestamp: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'sub-categories';
        value: number | SubCategory;
      } | null)
    | ({
        relationTo: 'shapes';
        value: number | Shape;
      } | null)
    | ({
        relationTo: 'occasions';
        value: number | Occasion;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'diamond-categories';
        value: number | DiamondCategory;
      } | null)
    | ({
        relationTo: 'color-stones';
        value: number | ColorStone;
      } | null)
    | ({
        relationTo: 'rate-gold';
        value: number | RateGold;
      } | null)
    | ({
        relationTo: 'rate-diamond';
        value: number | RateDiamond;
      } | null)
    | ({
        relationTo: 'making-rules';
        value: number | MakingRule;
      } | null)
    | ({
        relationTo: 'fx-rates';
        value: number | FxRate;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'collection-banners';
        value: number | CollectionBanner;
      } | null)
    | ({
        relationTo: 'collection-marketing-tiles';
        value: number | CollectionMarketingTile;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'trust-badges';
        value: number | TrustBadge;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'try-at-home-leads';
        value: number | TryAtHomeLead;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        zoom?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  sortOrder?: T;
  heroImage?: T;
  shortDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sub-categories_select".
 */
export interface SubCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  sortOrder?: T;
  heroImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shapes_select".
 */
export interface ShapesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  sortOrder?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "occasions_select".
 */
export interface OccasionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  sortOrder?: T;
  heroImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  code?: T;
  status?: T;
  slug?: T;
  displayName?: T;
  description?: T;
  category?: T;
  subCategory?: T;
  primaryShape?: T;
  isSolitaire?: T;
  isRing?: T;
  fulfillmentType?: T;
  stockQuantity?: T;
  heroImage?: T;
  defaultGoldColor?: T;
  heroImageYellow?: T;
  heroImageWhite?: T;
  heroImageRose?: T;
  gallery?:
    | T
    | {
        image?: T;
        goldColor?: T;
        id?: T;
      };
  fromPriceInr?: T;
  metals?:
    | T
    | {
        purity?: T;
        weightG?: T;
        id?: T;
      };
  diamonds?:
    | T
    | {
        role?: T;
        shape?: T;
        sizeMm?: T;
        weightCt?: T;
        count?: T;
        cut?: T;
        color?: T;
        clarity?: T;
        id?: T;
      };
  colorStones?:
    | T
    | {
        stone?: T;
        weightCt?: T;
        count?: T;
        id?: T;
      };
  designerNotes?: T;
  remarks?: T;
  complementaryProducts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "diamond-categories_select".
 */
export interface DiamondCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "color-stones_select".
 */
export interface ColorStonesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  grade?: T;
  ratePerCt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rate-gold_select".
 */
export interface RateGoldSelect<T extends boolean = true> {
  purity?: T;
  ratePerG?: T;
  source?: T;
  effectiveAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rate-diamond_select".
 */
export interface RateDiamondSelect<T extends boolean = true> {
  diamondCategory?: T;
  ctBandMin?: T;
  ctBandMax?: T;
  ratePerCt?: T;
  cut?: T;
  color?: T;
  clarity?: T;
  effectiveAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "making-rules_select".
 */
export interface MakingRulesSelect<T extends boolean = true> {
  metalType?: T;
  type?: T;
  wastagePct?: T;
  makingPerG?: T;
  minMaking?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fx-rates_select".
 */
export interface FxRatesSelect<T extends boolean = true> {
  currency?: T;
  inrPerUnit?: T;
  source?: T;
  effectiveAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  product?: T;
  rating?: T;
  title?: T;
  body?: T;
  authorName?: T;
  reviewDate?: T;
  verified?: T;
  approved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collection-banners_select".
 */
export interface CollectionBannersSelect<T extends boolean = true> {
  category?: T;
  title?: T;
  subtitle?: T;
  description?: T;
  imageUrl?: T;
  mobileImageUrl?: T;
  overlayOpacity?: T;
  ctaText?: T;
  ctaLink?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collection-marketing-tiles_select".
 */
export interface CollectionMarketingTilesSelect<T extends boolean = true> {
  category?: T;
  title?: T;
  description?: T;
  imageUrl?: T;
  ctaText?: T;
  ctaLink?: T;
  backgroundColor?: T;
  insertAfterNthProduct?: T;
  displayOrder?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trust-badges_select".
 */
export interface TrustBadgesSelect<T extends boolean = true> {
  icon?: T;
  label?: T;
  tooltip?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  fullName?: T;
  phone?: T;
  waOptIn?: T;
  segments?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "try-at-home-leads_select".
 */
export interface TryAtHomeLeadsSelect<T extends boolean = true> {
  customerName?: T;
  phone?: T;
  email?: T;
  address?: T;
  city?: T;
  state?: T;
  pincode?: T;
  productCode?: T;
  productName?: T;
  status?: T;
  leadSource?: T;
  referenceImages?:
    | T
    | {
        url?: T;
        id?: T;
      };
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderId?: T;
  cashfreeOrderId?: T;
  cashfreePaymentId?: T;
  paymentStatus?: T;
  fulfillmentStatus?: T;
  customerName?: T;
  customerPhone?: T;
  customerEmail?: T;
  shippingAddress?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        pincode?: T;
      };
  items?:
    | T
    | {
        productCode?: T;
        displayName?: T;
        qty?: T;
        metal?: T;
        goldColor?: T;
        diamondTier?: T;
        ringSize?: T;
        caratWeight?: T;
        unitPriceInr?: T;
        engraving?: T;
        id?: T;
      };
  subtotalInr?: T;
  gstInr?: T;
  totalInr?: T;
  orderNotes?: T;
  gstInvoiceRequested?: T;
  trackingInfo?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  visitorId?: T;
  sessionId?: T;
  eventName?: T;
  eventData?: T;
  pageUrl?: T;
  referrer?: T;
  userAgent?: T;
  ipAddress?: T;
  utmSource?: T;
  utmMedium?: T;
  utmCampaign?: T;
  utmContent?: T;
  revenue?: T;
  currency?: T;
  orderId?: T;
  blogSlug?: T;
  scrollDepth?: T;
  timeOnPage?: T;
  timestamp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Site-wide configuration. Disclaimer text, badges, copy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Found in Meta Events Manager → your pixel → Settings. A 15–16 digit number.
   */
  metaPixelId?: string | null;
  /**
   * Found in GA4 Admin → Data Streams → your stream → Measurement ID. Starts with 'G-'.
   */
  ga4MeasurementId?: string | null;
  /**
   * Found in TikTok Ads Manager → Assets → Events → your pixel. Alphanumeric string.
   */
  tiktokPixelId?: string | null;
  /**
   * International format. Used in the Design Advisor and Try-at-Home WA links.
   */
  whatsappNumber?: string | null;
  /**
   * If you use GTM, enter the container ID. GTM can manage all other pixels, so leave the above IDs blank if GTM handles them.
   */
  googleTagManagerId?: string | null;
  /**
   * Switch to Production when you are ready to accept real payments.
   */
  cashfreeEnvironment?: ('sandbox' | 'production') | null;
  /**
   * Percentage of order total charged at checkout. 100 = full payment upfront (default). Lower values (e.g. 50) create a deposit flow.
   */
  checkoutDepositPct?: number | null;
  /**
   * Currency shown at checkout. Cashfree supports INR.
   */
  checkoutCurrency?: 'INR' | null;
  /**
   * Shown on PDP and quote PDFs for made-to-order products.
   */
  madeToOrderDisclaimer?: string | null;
  /**
   * Shown on PDP for ready-stock products.
   */
  readyStockBadgeText?: string | null;
  readyStockPriceNote?: string | null;
  /**
   * How long a generated quote stays valid before gold-rate movement requires a fresh quote.
   */
  quoteValidityDays?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Master switches for every external integration. When a switch is OFF, a safe manual fallback runs. Flip ON only after you've tested the integration.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feature-flags".
 */
export interface FeatureFlag {
  id: number;
  wa_business_api?: boolean | null;
  wa_shared_inbox?: boolean | null;
  wa_login?: boolean | null;
  ai_draft_replies?: boolean | null;
  ai_web_chatbot?: boolean | null;
  ai_voice_agent?: boolean | null;
  ai_reference_image_search?: boolean | null;
  gold_rate_live_ibja?: boolean | null;
  gold_rate_auto_recompute?: boolean | null;
  fx_live?: boolean | null;
  checkout_cashfree?: boolean | null;
  checkout_gst_invoice_pdf?: boolean | null;
  shipping_serviceability?: boolean | null;
  meta_capi_server_side?: boolean | null;
  email_transactional?: boolean | null;
  email_campaigns?: boolean | null;
  campaigns_scheduled_sends?: boolean | null;
  search_semantic_pgvector?: boolean | null;
  similar_products_vector?: boolean | null;
  scraper_competitor_designs?: boolean | null;
  wallet_cashback_engine?: boolean | null;
  wallet_loyalty_points?: boolean | null;
  i18n_hindi?: boolean | null;
  i18n_other_languages?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Controls the 'Try at Home' lead-generation card shown on product pages. Leads are saved under CRM → Try at Home Leads.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "try-at-home-settings".
 */
export interface TryAtHomeSetting {
  id: number;
  enabled?: boolean | null;
  /**
   * Heading shown on the card
   */
  title?: string | null;
  /**
   * Body text shown below the heading
   */
  description?: string | null;
  /**
   * CTA button label
   */
  buttonText?: string | null;
  /**
   * Optional lifestyle image shown on the left of the card (landscape works best)
   */
  image?: (number | null) | Media;
  /**
   * Optional small-print shown below the form (e.g. 'Available in Jaipur & Delhi only')
   */
  disclaimer?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Control every section on the homepage. Use '+ Add Block' to add a new section, and drag the handles to reorder them.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  /**
   * Each row is one section on the homepage. Drag to reorder. Leave empty to show the default layout.
   */
  sections?:
    | (
        | {
            /**
             * Main headline text.
             */
            heading: string;
            /**
             * Optional paragraph below the headline.
             */
            subheading?: string | null;
            /**
             * Desktop hero image. Recommended: 1400 × 600 px. Drag & drop, browse, or paste a URL.
             */
            imageUrl?: string | null;
            /**
             * Optional portrait crop for phones (≤ 640 px). Recommended: 640 × 800 px. Falls back to desktop image.
             */
            mobileImageUrl?: string | null;
            /**
             * Background colour shown when no image is set, or as overlay fallback.
             */
            backgroundColor?: ('navy' | 'cream' | 'white') | null;
            /**
             * Primary button label — e.g. 'Shop Rings'
             */
            primaryCtaText?: string | null;
            /**
             * Primary button URL — e.g. '/collections/rings'
             */
            primaryCtaLink?: string | null;
            /**
             * Secondary button label (optional)
             */
            secondaryCtaText?: string | null;
            /**
             * Secondary button URL (optional)
             */
            secondaryCtaLink?: string | null;
            /**
             * Split mode places the AI chat box on the right half of the hero. Works best with a background image.
             */
            splitMode?: ('full' | 'split-chat') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero-banner';
          }
        | {
            /**
             * Small uppercase label above the title.
             */
            eyebrow?: string | null;
            title: string;
            /**
             * Add one row per category card. Drag to reorder.
             */
            items?:
              | {
                  category: number | Category;
                  /**
                   * Card background image. Recommended: 500 × 625 px (portrait). Falls back to navy gradient.
                   */
                  imageUrl?: string | null;
                  /**
                   * Override the category name shown on the card (optional).
                   */
                  labelOverride?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'category-grid';
          }
        | {
            /**
             * Desktop banner image. Recommended: 1400 × 500 px. Drag & drop, browse, or paste a URL.
             */
            imageUrl: string;
            /**
             * Optional portrait crop for phones (≤ 640 px). Recommended: 640 × 800 px.
             */
            mobileImageUrl?: string | null;
            /**
             * Alt text for screen readers and SEO.
             */
            altText?: string | null;
            /**
             * Makes the entire banner clickable — e.g. '/collections/earrings'.
             */
            link?: string | null;
            /**
             * Optional heading overlaid on the image.
             */
            overlayText?: string | null;
            /**
             * CTA button label shown on the overlay.
             */
            ctaText?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image-banner';
          }
        | {
            /**
             * Small uppercase label above the title.
             */
            eyebrow?: string | null;
            title?: string | null;
            backgroundColor?: ('cream' | 'white' | 'navy') | null;
            /**
             * Each shape chip links to this category URL with ?shape=<slug> appended — e.g. '/collections/rings'.
             */
            linkToCategory?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'shape-grid';
          }
        | {
            /**
             * Optional small uppercase label above the title.
             */
            eyebrow?: string | null;
            /**
             * Optional section heading.
             */
            title?: string | null;
            backgroundColor?: ('white' | 'cream' | 'navy') | null;
            /**
             * Each item is one column in the strip.
             */
            items?:
              | {
                  /**
                   * Paste an emoji (e.g. ✦ 💎 ✓ ★). Windows: Win+.  •  Mac: Ctrl+Cmd+Space to open the emoji picker.
                   */
                  icon?: string | null;
                  /**
                   * Optional: upload a small icon image (PNG/SVG, square ~64 px). Shown instead of the emoji above if both are set.
                   */
                  iconUrl?: string | null;
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'promise-strip';
          }
        | {
            /**
             * Small uppercase label above the title.
             */
            eyebrow?: string | null;
            title: string;
            /**
             * Select up to 8 products to feature. Drag to reorder.
             */
            items?:
              | {
                  /**
                   * Step 1 — Select a category to filter the products below.
                   */
                  category?: (number | null) | Category;
                  /**
                   * Step 2 — Pick a product. Selecting a category above narrows this list automatically.
                   */
                  product: number | Product;
                  /**
                   * Step 3 — Optional: pin a specific metal so the card links directly to that variant on the PDP.
                   */
                  metal?: ('' | '9K' | '14K' | '18K' | '22K' | 'Silver925' | 'Platinum') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featured-products';
          }
        | {
            /**
             * Section heading shown above the chat initiator.
             */
            heading?: string | null;
            /**
             * Short paragraph below the heading.
             */
            subheading?: string | null;
            /**
             * Placeholder text inside the chat input box.
             */
            placeholderText?: string | null;
            /**
             * Label on the button that opens the chat.
             */
            ctaLabel?: string | null;
            /**
             * WhatsApp number for human escalation (include country code, e.g. +919829115205).
             */
            whatsappNumber?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'customization-chat';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Build the Design Advisor questionnaire by adding, removing, and reordering steps. Each step can route to any other by Step Key. Changes go live within ~1 minute.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chatbot-config".
 */
export interface ChatbotConfig {
  id: number;
  /**
   * The Step Key of the first step shown to the customer. Default: 'occasion'.
   */
  entryStepKey?: string | null;
  /**
   * Add blocks to build your questionnaire. Drag to reorder. Use 'Choice Step' for button grids, 'Describe Step' for free-text input, 'Upload Step' for image uploads. Use '__results__' or '__contact__' in 'Go to Step' fields to terminate the flow.
   */
  steps?:
    | (
        | {
            /**
             * Unique identifier used in 'Go to Step' fields (e.g. 'occasion', 'budget'). No spaces.
             */
            stepKey: string;
            questionText: string;
            subtitle?: string | null;
            /**
             * Each row is a tappable button. 'Go to Step' must match another step's key, or use __results__ (show product grid) or __contact__ (show lead form only).
             */
            options?:
              | {
                  label: string;
                  emoji?: string | null;
                  /**
                   * e.g. 'budget' or '__results__'
                   */
                  goToStepKey?: string | null;
                  categorySlug?: ('rings' | 'necklaces' | 'earrings' | 'bracelets' | '') | null;
                  behavior?: ('normal' | 'prefer-chat') | null;
                  /**
                   * ₹ min (0 = none)
                   */
                  minPrice?: number | null;
                  /**
                   * ₹ max (0 = none)
                   */
                  maxPrice?: number | null;
                  /**
                   * Pre-filled WhatsApp message style
                   */
                  waStyle?: ('standard' | 'reference' | 'expert' | 'describe') | null;
                  /**
                   * Custom event name, e.g. "WeddingRingChosen"
                   */
                  pixelEvent?: string | null;
                  /**
                   * e.g. {"occasion":"Wedding"}
                   */
                  pixelParams?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'choiceStep';
          }
        | {
            /**
             * Unique identifier, e.g. 'describe'
             */
            stepKey: string;
            questionText: string;
            subtitle?: string | null;
            placeholder?: string | null;
            /**
             * Small chips the customer can tap to auto-append words to their description. Include emoji in the label if you want.
             */
            hints?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Step key to navigate to after the customer submits. Usually '__results__'.
             */
            goToStepKey?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'describeStep';
          }
        | {
            /**
             * Unique identifier, e.g. 'upload'
             */
            stepKey: string;
            questionText: string;
            subtitle?: string | null;
            /**
             * Step key to navigate to after the customer continues. Usually '__results__'.
             */
            goToStepKey?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'uploadStep';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  metaPixelId?: T;
  ga4MeasurementId?: T;
  tiktokPixelId?: T;
  whatsappNumber?: T;
  googleTagManagerId?: T;
  cashfreeEnvironment?: T;
  checkoutDepositPct?: T;
  checkoutCurrency?: T;
  madeToOrderDisclaimer?: T;
  readyStockBadgeText?: T;
  readyStockPriceNote?: T;
  quoteValidityDays?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feature-flags_select".
 */
export interface FeatureFlagsSelect<T extends boolean = true> {
  wa_business_api?: T;
  wa_shared_inbox?: T;
  wa_login?: T;
  ai_draft_replies?: T;
  ai_web_chatbot?: T;
  ai_voice_agent?: T;
  ai_reference_image_search?: T;
  gold_rate_live_ibja?: T;
  gold_rate_auto_recompute?: T;
  fx_live?: T;
  checkout_cashfree?: T;
  checkout_gst_invoice_pdf?: T;
  shipping_serviceability?: T;
  meta_capi_server_side?: T;
  email_transactional?: T;
  email_campaigns?: T;
  campaigns_scheduled_sends?: T;
  search_semantic_pgvector?: T;
  similar_products_vector?: T;
  scraper_competitor_designs?: T;
  wallet_cashback_engine?: T;
  wallet_loyalty_points?: T;
  i18n_hindi?: T;
  i18n_other_languages?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "try-at-home-settings_select".
 */
export interface TryAtHomeSettingsSelect<T extends boolean = true> {
  enabled?: T;
  title?: T;
  description?: T;
  buttonText?: T;
  image?: T;
  disclaimer?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        'hero-banner'?:
          | T
          | {
              heading?: T;
              subheading?: T;
              imageUrl?: T;
              mobileImageUrl?: T;
              backgroundColor?: T;
              primaryCtaText?: T;
              primaryCtaLink?: T;
              secondaryCtaText?: T;
              secondaryCtaLink?: T;
              splitMode?: T;
              id?: T;
              blockName?: T;
            };
        'category-grid'?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?:
                | T
                | {
                    category?: T;
                    imageUrl?: T;
                    labelOverride?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'image-banner'?:
          | T
          | {
              imageUrl?: T;
              mobileImageUrl?: T;
              altText?: T;
              link?: T;
              overlayText?: T;
              ctaText?: T;
              id?: T;
              blockName?: T;
            };
        'shape-grid'?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              backgroundColor?: T;
              linkToCategory?: T;
              id?: T;
              blockName?: T;
            };
        'promise-strip'?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              backgroundColor?: T;
              items?:
                | T
                | {
                    icon?: T;
                    iconUrl?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'featured-products'?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?:
                | T
                | {
                    category?: T;
                    product?: T;
                    metal?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'customization-chat'?:
          | T
          | {
              heading?: T;
              subheading?: T;
              placeholderText?: T;
              ctaLabel?: T;
              whatsappNumber?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chatbot-config_select".
 */
export interface ChatbotConfigSelect<T extends boolean = true> {
  entryStepKey?: T;
  steps?:
    | T
    | {
        choiceStep?:
          | T
          | {
              stepKey?: T;
              questionText?: T;
              subtitle?: T;
              options?:
                | T
                | {
                    label?: T;
                    emoji?: T;
                    goToStepKey?: T;
                    categorySlug?: T;
                    behavior?: T;
                    minPrice?: T;
                    maxPrice?: T;
                    waStyle?: T;
                    pixelEvent?: T;
                    pixelParams?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        describeStep?:
          | T
          | {
              stepKey?: T;
              questionText?: T;
              subtitle?: T;
              placeholder?: T;
              hints?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              goToStepKey?: T;
              id?: T;
              blockName?: T;
            };
        uploadStep?:
          | T
          | {
              stepKey?: T;
              questionText?: T;
              subtitle?: T;
              goToStepKey?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}